---
  - name: AWX | Create dirs
    file: path="{{ item }}" state="directory" owner="{{ awx_user }}"
    with_items:
      - "{{ awx_base_dir }}"
      - "{{ awx_data_dir }}"
      - "{{ awx_projects_dir }}"
    become: yes
    tags:
      - awx

  - name: AWX | Ensure ansible
    pip:
      name: ansible
      state: present
      executable: "{{ preffered_pip }}"
    retries: 3
    register: result
    until: result is not failed
    become: yes
    tags:
      - awx

  - name: AWX | Ensure ansible-tower-cli
    pip:
      name: ansible-tower-cli
      state: present
      executable: "{{ preffered_pip }}"
    retries: 3
    register: result
    until: result is not failed
    become: yes
    tags:
      - awx

  - name: AWX | Clone repo
    git:
      repo: "https://github.com/ansible/awx.git"
      dest: "{{ awx_repo_dir }}"
      version: "{{ awx_version }}"
    tags:
      - awx

  - name: Template awx installation command.
    template:
      src: awx_install.sh.j2
      dest: "{{ awx_base_dir }}/awx_install.sh"
      mode: "u=rwx,g=rx,o="
    become: yes
    tags:
      - awx

  - name: Run the AWX installation playbook.
    command: >
      ansible-playbook -i inventory install.yml
      -e postgres_data_dir={{ awx_data_dir }}
      -e project_data_dir={{ awx_projects_dir }}
      -e awx_task_hostname=awx
      -e awx_web_hostname=awxweb
      -e host_port={{ awx_host_port }}
      -e docker_compose_dir={{ awx_base_dir }}
      -e pg_username=awx
      -e pg_password=awxpass
      -e pg_database=awx
      -e pg_port=5432
      -e rabbitmq_password=awxpass
      -e rabbitmq_erlang_cookie=cookiemonster
      -e admin_user={{ awx_admin_user }}
      -e admin_password={{ awx_admin_pass }}
      -e create_preload_data=True
      -e secret_key=awxsecret
      -e use_docker_compose={{ option_use_dockercompose }}
      -e ansible_python_interpreter={{ preffered_ansible_python_interpreter }}
# pg_hostname=postgresql
    args:
      chdir: "{{ awx_repo_dir }}/installer"
    tags:
      - awx
      - skip_ansible_lint
