# sa-docker 1.0.0
  - name: Docker | Check if is present
    command: test -x /usr/bin/docker
    ignore_errors: yes
    register: docker_present
    tags:
        -docker

  - name: Docker | Install dependencies
    apt: name="{{ item }}" state="present"
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    when: docker_present is failed and ansible_os_family == "Debian"
    become: yes
    tags:
        -docker


  - name: Docker | Add docker gpg keys
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present    
    when: docker_present is failed and ansible_os_family == "Debian"
    become: yes
    tags:
        -docker

  - block:

      - name: Docker | Add docker  repo
        apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
          state: present
          filename: docker
        become: yes
        tags:
          - docker

      - name: Docker | Install docker
        apt: 
          name: "docker-ce"
          state: "present"
          update_cache: "yes"
        become: yes
        tags:
          - docker

    when: docker_present is failed and ansible_os_family == "Debian"



  - name: Docker | Install docker via web installer
    shell: wget -qO- https://get.docker.com/ | sh
    when:  docker_present is failed
    become: yes
    tags:
        -docker

  - name: Docker | Add current user to docker group
    user: name={{ deploy_user | default(ansible_user_id) }} groups=docker append=yes
    become: yes
    tags:
        -docker

  - name: Docker | Start and enable service
    service: name=docker state=restarted enabled=yes
    when: docker_test is not defined
    become: yes
    tags:
        -docker


